services:
  certs:
    container_name: oe-certs
    image: certgen
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.certs

  oe.openelis.org:
    container_name: kapsiki-openelis-backend
    build:
      context: .
    image: kapsiki/kapsiki-openelis-backend


  fhir.openelis.org:
    container_name: kapsiki-openelis-fhir-api
    build:
      context: ./fhir
      dockerfile: ./Dockerfile
    image: kapsiki/kapsiki-openelis-fhir-api

  frontend.openelis.org:
    container_name: kapsiki-openelis-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    image: kapsiki/kapsiki-openelis-frontend

  proxy:
    container_name: kapsiki-openelis-proxy 
    build:
      context: ./nginx-proxy
      dockerfile: ./Dockerfile
    image: kapsiki/kapsiki-openelis-proxy
